### ISSUE TITLE
Vitesse par défaut durant une transformation

### ISSUE THREAD

**Issue by Nolat** [adgranger/foundryvtt-dnd5e-lang-fr-fr#191]
https://github.com/adgranger/foundryvtt-dnd5e-lang-fr-fr/blob/7b5d86872572f572680abcf763ed1bc65a33718c/babele-register.js#L79-L94

Cette partie du code pose problème lorsque l'on veux transformer un token. Par exemple quand un druide utilise sa forme sauvage pour devenir un cheval de selle, au lieu d'avoir une vitesse à 18m, il aura une vitesse de 9m.

**Comment by Enielka** [comment]
Pourrais-tu apporter plus de précision sur les moyens de reproduire, car je ne reproduis pas le problème avec la 4.1.2 du système et la 4.1.1.0 du module dnd5e fr

Peux-tu me dire la version du système, la version du module dnd5e fr et comment tu utilises la forme sauvage du druide ?

Merci.

**Comment by AlexisArcs** [comment]
**Version du système :** 4.1.2
**Version du module:** 4.1.1.0

**Pour reproduire :** 
1. Activer l'option "_Conversions automatiques_" du module
2. Déposer un acteur sur la scène
3. Drag & drop un autre acteur, avec une vitesse différente, sur le précédent
4. Cliquer sur le bouton "Forme sauvage"
<img width="904" alt="image" src="https://github.com/user-attachments/assets/2b1c86b7-5953-41a5-bf5d-31c5ca9f8a01">

Sur ces images, on peux voir que la vitesse de l'acteur "Fir" est de 12 mètres, que celle du cheval de selle est de 18 mètres. Mais après la transformation, la vitesse est de 9 mètres au lieu de 18.

<img width="192" alt="image" src="https://github.com/user-attachments/assets/029d8acf-bf22-4dcf-a95f-92c08aea02be">
<img width="255" alt="image" src="https://github.com/user-attachments/assets/532c0f3e-6c86-4c04-a4ce-d205d8317c7b">
<img width="180" alt="image" src="https://github.com/user-attachments/assets/21d032ba-b0a8-4f53-88c9-b3bdaba3dd49">

Le bug n'apparait pas lorsque l'option "_Conversions automatiques_" est désactivée.

**Comment by Nolat** [comment]
**Version du système :** 4.1.2
**Version du module:** 4.1.1.0

**Pour reproduire :** 
1. Activer l'option "_Conversions automatiques_" du module
2. Déposer un acteur sur la scène
3. Drag & drop un autre acteur, avec une vitesse différente, sur le précédent
4. Cliquer sur le bouton "Forme sauvage"
<img width="904" alt="image" src="https://github.com/user-attachments/assets/2b1c86b7-5953-41a5-bf5d-31c5ca9f8a01">

Sur ces images, on peux voir que la vitesse de l'acteur "Fir" est de 12 mètres, que celle du cheval de selle est de 18 mètres. Mais après la transformation, la vitesse est de 9 mètres au lieu de 18.

<img width="192" alt="image" src="https://github.com/user-attachments/assets/029d8acf-bf22-4dcf-a95f-92c08aea02be">
<img width="255" alt="image" src="https://github.com/user-attachments/assets/532c0f3e-6c86-4c04-a4ce-d205d8317c7b">
<img width="180" alt="image" src="https://github.com/user-attachments/assets/21d032ba-b0a8-4f53-88c9-b3bdaba3dd49">

Le bug n'apparait pas lorsque l'option "_Conversions automatiques_" est désactivée.

**Comment by Enielka** [comment]
En utilisant ta méthode de reproduction, je ne reproduis toujours pas le bug.

Avec le système, il n'est pas possible de drag & drop un acteur sur un autre directement sur la scène. La transformation s'effectue lors d'un drag & drop d'un acteur sur la feuille de personnage d'un autre acteur (qu'il soit sur la scène ou non).

En regardant tes screens, j'ai l'impression que tu utilises d'autres module. Si c'est le cas, essaye de reproduire le bug dans monde avec juste le module FR d'activé.

Si le bug n'est plus reproduit avec juste le module FR d'activé, active un par un (en désactivant le précédant) les modules présents sur le monde où le bug a été constaté. 

Si le bug n'est toujours pas reproduit en activant un par un les modules, active les modules un par un, mais en laissant les modules précédant activés.

Cela permettra de voir si un module est responsable du bug et lequel.

**Comment by Nolat** [comment]
Oui c'est une erreur de ma part, il faut bien drag & drop sur la fiche et non sur l'acteur.

J'ai bel et bien d'autres modules, mais je viens de refaire la même chose sur un monde avec seulement les modules suivants
<img width="690" alt="image" src="https://github.com/user-attachments/assets/97879b41-ba60-416c-93a8-210981f9d4bd">

 **Pour reproduire (plus en détail):** 
1. Activer l'option "_Conversions automatiques_" du module
2. Créer un nouvel acteur (PJ ou PNJ)
<img width="244" alt="image" src="https://github.com/user-attachments/assets/e7b8af15-26d4-49ba-8c1e-5b6bf3e097ab">

3. Drag & drop un autre acteur, avec une vitesse différente, sur la fiche de l'acteur précédent
4. Cliquer sur le bouton "Forme sauvage"
<img width="411" alt="image" src="https://github.com/user-attachments/assets/6f684f31-ec73-4b75-b4ea-401a828395b1">

<img width="369" alt="image" src="https://github.com/user-attachments/assets/3dd60f0a-ec26-4442-80c0-18840d719b5f">

**Comment by Nolat** [comment]
Le bug n'est bel et bien pas reproductible en utilisant comme acteur **à transformer**, un acteur venant d'un compendium.

**Comment by Enielka** [comment]
Merci pour tes retours, c'est enfin reproduit de mon côté. Je regarde pour corrigé ça.
