### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by gfrancqu** [adgranger/foundryvtt-dnd5e-lang-fr-fr#38]
Hello, j'ai un problème pour activer le module depuis la mise à jour du systeme dnd5:

![Screenshot_20240203_123535_Chrome](https://github.com/adgranger/foundryvtt-dnd5e-lang-fr-fr/assets/11816129/1142e1db-099d-49a5-b5f6-16fa35d16520)

Et merci pour ce travail !

**Comment by adgranger** [comment]
Normalement ça devrait tourner avec la mise à jour
