### ISSUE TITLE
Aptitudes de monstres non convertis.

### ISSUE THREAD

**Issue by Padhiver** [adgranger/foundryvtt-dnd5e-lang-fr-fr#72]
Cf : https://discord.com/channels/715943353409339425/716213970297552897/1217830132115439706

J'ai l'impression que c'est sur les aptitudes qui ont une traduction forcée pour être différenciées de la version générique présente dans le compendium Monster Feature.

**Comment by adgranger** [comment]
Problème identifié, il faut déplacer les traductions d'aptitudes de monstres de dnd5e.monsters.json vers dnd5e.monsterfeatures.json

En passant par l'id pour éviter les conflits de noms

![image](https://github.com/adgranger/foundryvtt-dnd5e-lang-fr-fr/assets/131141262/69f59582-005e-4041-8e86-cdeec59ba6eb)

**Comment by adgranger** [comment]
- [ ] Aarakocre
- [x] Aboleth
- [ ] Abomination yuan-tie
- [ ] Acérérak
- [ ] Acolyte
- [ ] Aigle
- [ ] Aigle géant
- [ ] Allosaure
- [ ] Âme en peine
- [ ] Androsphinx
- [ ] Ankheg
- [ ] Ankylosaure
- [x] Araignée
- [ ] Araignée de phase
- [x] Araignée géante
- [x] Araignée-loup géante
- [ ] Arbre éveillé
- [ ] Arbre infecté
- [ ] Arbuste éveillé
- [ ] Arcanaloth
- [ ] Archimage
- [ ] Armure animée
- [ ] Assassin
- [ ] Autrache
- [ ] Avatar de la Mort
- [ ] Azer
- [x] Babélien
- [ ] Babouin
- [x] Balor
- [ ] Bandit
- [ ] Bandit, capitaine
- [ ] Banshie
- [ ] Barlgura
- [ ] Basilic
- [ ] Béhir
- [x] Belette
- [x] Belette géante
- [ ] Berserker
- [ ] Bête éclipsante
- [x] Blaireau
- [x] Blaireau géant
- [ ] Blême
- [ ] Brutacien
- [ ] Buisson infecté
- [ ] Bulette
- [ ] Camdescriptionn
- [ ] Centaure
- [ ] Cerf
- [ ] Chacal
- [ ] Chacalidé
- [ ] Chameau
- [ ] Charognard rampant
- [ ] Chasme
- [ ] Chat
- [ ] Chauve-souris
- [ ] Chauve-souris géante
- [ ] Cheval de selle
- [ ] Cheval de trait
- [ ] Chevalier
- [ ] Chevalier de la mort
- [ ] Chèvre
- [ ] Chèvre géante
- [ ] Chien du trépas
- [ ] Chien esquiveur
- [ ] Chimère
- [ ] Chouette
- [ ] Chouette géante
- [ ] Chuul
- [ ] Cockatrice
- [ ] Combattant (niv 1)
- [ ] Combattant (niv 2)
- [ ] Combattant (niv 3)
- [ ] Combattant (niv 4)
- [ ] Combattant (niv 5)
- [ ] Combattant (niv 6)
- [ ] Consul de fer
- [ ] Corbeau
- [ ] Corbeau-garou
- [ ] Couatl
- [ ] Crabe
- [ ] Crabe géant
- [ ] Crânefeu
- [ ] Crapaud géant
- [ ] Criard
- [ ] Crocodile
- [ ] Crocodile géant
- [ ] Crokek'toeck
- [ ] Cube gélatineux
- [ ] Cyclope
- [ ] Dao
- [ ] Demi-dragon rouge, vétéran
- [ ] Demi-liche
- [ ] Demi-ogre
- [ ] Démon des ombres
- [ ] Destrier
- [ ] Destrier noir
- [ ] Déva
- [ ] Dévoreur d'intellect
- [ ] Diable barbelé
- [ ] Diable barbu
- [ ] Diable cornu
- [ ] Diable des chaînes
- [ ] Diable épineux
- [ ] Diable gelé
- [ ] Diable osseux
- [ ] Diablotin
- [ ] Diantrefosse
- [ ] Djinn
- [ ] Doppelganger
- [ ] Dracoliche bleue, adulte
- [ ] Dragon blanc, adulte
- [ ] Dragon blanc, jeune
- [ ] Dragon blanc, nouveau-né
- [ ] Dragon blanc, vénérable
- [ ] Dragon bleu, jeune
- [ ] Dragon bleu, nouveau-né
- [ ] Dragon bleu, vénérable
- [ ] Dragon d'airain, adulte
- [ ] Dragon d'airain, jeune
- [ ] Dragon d'airain, nouveau-né
- [ ] Dragon d'airain, vénérable
- [ ] Dragon d'argent, adulte
- [ ] Dragon d'argent, jeune
- [ ] Dragon d'argent, nouveau-né
- [ ] Dragon d'argent, vénérable
- [ ] Dragon de bronze, adulte
- [ ] Dragon de bronze, jeune
- [ ] Dragon de bronze, nouveau-né
- [ ] Dragon de bronze, vénérable
- [ ] Dragon de cuivre, adulte
- [ ] Dragon de cuivre, jeune
- [ ] Dragon de cuivre, nouveau-né
- [ ] Dragon de cuivre, vénérable
- [ ] Dragon d'ombre rouge, jeune
- [ ] Dragon d'or, adulte
- [ ] Dragon d'or, jeune
- [ ] Dragon d'or, nouveau-né
- [ ] Dragon d'or, vénérable
- [ ] Dragon féerique
- [ ] Dragon noir adulte
- [ ] Dragon noir adulte
- [ ] Dragon noir, jeune
- [ ] Dragon noir, nouveau-né
- [ ] Dragon noir, vénérable
- [ ] Dragon rouge, adulte
- [ ] Dragon rouge, jeune
- [ ] Dragon rouge, nouveau-né
- [ ] Dragon rouge, vénérable
- [ ] Dragon vert, adulte
- [ ] Dragon vert, jeune
- [ ] Dragon vert, nouveau-né
- [ ] Dragon vert, vénérable
- [ ] Dragon-tortue
- [ ] Dretch
- [ ] Drider
- [ ] Drow
- [ ] Drow, guerrier d'élite
- [ ] Drow, mage
- [ ] Drow, prêtresse de Lolth
- [ ] Druide
- [ ] Dryade
- [ ] Duergar
- [ ] Duodrone
- [ ] Ecclésiastique
- [ ] Éclaireur
- [ ] Éfrit
- [ ] Élan
- [ ] Élan géant
- [ ] Élémentaire de la terre
- [ ] Élémentaire de l'air
- [ ] Élémentaire de l'eau
- [ ] Élémentaire du feu
- [ ] Éléphant
- [ ] Empyréen
- [ ] Enlaceur
- [ ] Épaulard
- [ ] Épée volante
- [ ] Épouvantail
- [ ] Érinye
- [ ] Espion
- [ ] Esprit follet
- [ ] Ettercap
- [ ] Ettin
- [ ] Expert (niv 1)
- [ ] Expert (niv 2)
- [ ] Expert (niv 3)
- [ ] Expert (niv 4)
- [ ] Expert (niv 5)
- [ ] Expert (niv 6)
- [ ] Fanatique de secte
- [ ] Fantôme
- [ ] Faucheur de Bhaal
- [ ] Faucon
- [ ] Faucon de sang
- [ ] Feu follet
- [ ] Flagelleur des crânes de Myrkul
- [ ] Flagelleur mental
- [ ] Flumph
- [ ] Fomorien
- [ ] Galeb duhr
- [ ] Gantelet noir de Baine
- [ ] Garde
- [ ] Garde animé
- [ ] Gargouille
- [ ] Géant des collines
- [ ] Géant des nuages
- [ ] Géant des pierres
- [ ] Géant des tempêtes
- [ ] Géant du feu
- [ ] Géant du givre
- [ ] Gelée ocre
- [ ] Githyanki, chevalier
- [ ] Githyanki, guerrier
- [ ] Githzerai, moine
- [ ] Githzerai, zerth
- [ ] Glabrezu
- [ ] Gladiateur
- [ ] Gnoll
- [ ] Gnoll, chef de meute
- [ ] Gnoll, croc de Yeenoghu
- [ ] Gnome des profondeurs
- [ ] Gnome des profondeurs (svirfnebelin)
- [ ] Gobelin
- [ ] Gobelin, chef
- [ ] Gobelours
- [ ] Gobelours, chef
- [ ] Golem d'argile
- [ ] Golem de chair
- [ ] Golem de fer
- [ ] Golem de pierre
- [ ] Gorgone
- [ ] Goristro
- [ ] Goule
- [ ] Grand singe
- [ ] Grell
- [ ] Grenouille
- [ ] Grenouille géante
- [ ] Grick
- [ ] Grick dominant
- [ ] Griffon
- [ ] Guenaude aquatique
- [ ] Guenaude nocturne
- [ ] Guenaude verte
- [ ] Guêpe géante
- [ ] Guêpe infernale
- [ ] Guerrier tribal
- [ ] Gynosphinx
- [ ] Halaster Blackcloak
- [ ] Harpie
- [ ] Hezrou
- [ ] Hibours
- [ ] Hippocampe
- [ ] Hippocampe géant
- [ ] Hippogriffe
- [ ] Hobgobelin
- [ ] Hobgobelin, capitaine
- [ ] Hobgobelin, seigneur de guerre
- [ ] Homme-lézard, chaman
- [ ] Homoncule
- [ ] Horreur casquée
- [ ] Horreur crochue
- [ ] Hydre
- [ ] Hyène
- [ ] Hyène géante
- [ ] Jarlaxle Baenre
- [ ] Kenku
- [ ] Kobold
- [ ] Kobold ailé
- [ ] Kraken
- [ ] Kuo-toa
- [ ] Kuo-toa, archiprêtre
- [ ] Kuo-toa, fouet
- [ ] Laeral Silverhand
- [ ] Lame de nuit
- [ ] Lamie
- [ ] Lanceur de sorts (guérisseur, niv 1)
- [ ] Lanceur de sorts (guérisseur, niv 2)
- [ ] Lanceur de sorts (guérisseur, niv 3)
- [ ] Lanceur de sorts (guérisseur, niv 4)
- [ ] Lanceur de sorts (guérisseur, niv 5)
- [ ] Lanceur de sorts (guérisseur, niv 6)
- [ ] Lanceur de sorts (mage, niv 1)
- [ ] Lanceur de sorts (mage, niv 2)
- [ ] Lanceur de sorts (mage, niv 3)
- [ ] Lanceur de sorts (mage, niv 4)
- [ ] Lanceur de sorts (mage, niv 5)
- [ ] Lanceur de sorts (mage, niv 6)
- [ ] Lémure
- [ ] Lézard
- [ ] Lézard géant
- [ ] Liane meurtrière
- [ ] Liche
- [ ] Licorne
- [ ] Lierre infecté
- [ ] Lierre musqué jaune
- [ ] Lion
- [ ] Loup
- [ ] Loup arctique
- [ ] Loup sanguinaire
- [ ] Loup-garou
- [ ] Mage
- [ ] Magmatique
- [ ] Main rampante
- [ ] Maître des âmes
- [ ] Malfrat
- [ ] Mammouth
- [ ] Mâne
- [ ] Manshoon
- [ ] Mante obscure
- [ ] Manteleur
- [ ] Manticore
- [ ] Maride
- [ ] Marilith
- [ ] Mastodonte des ombres
- [ ] Méduse
- [ ] Membre de secte
- [ ] Méphite de boue
- [ ] Méphite de fumée
- [ ] Méphite de glace
- [ ] Méphite de magma
- [ ] Méphite de poussière
- [ ] Méphite de vapeur
- [ ] Merrow
- [ ] Mezzoloth
- [ ] Mille-pattes géant
- [ ] Mimique
- [ ] Minotaure
- [ ] Minotaure squelette
- [ ] Moisissure violette
- [ ] Molosse
- [ ] Molosse infernal
- [ ] Momie
- [ ] Momie auguste
- [ ] Monodrone
- [ ] Mouche géante
- [ ] Mule
- [ ] Myconide, adulte
- [ ] Myconide, souverain
- [ ] Naga corrupteur
- [ ] Naga gardien
- [ ] Naga osseux
- [ ] Nalfeshnie
- [ ] Nécromite of Myrkul
- [ ] Nécrophage
- [ ] Noble
- [ ] Nothic
- [ ] Nuée d'araignées
- [ ] Nuée de chauves-souris
- [ ] Nuée de coléoptères
- [ ] Nuée de corbeaux
- [ ] Nuée de guêpes
- [ ] Nuée de mille-pattes
- [ ] Nuée de piranhas
- [ ] Nuée de rats
- [ ] Nuée de serpents venimeux
- [ ] Nuée d'insectes
- [ ] Nycaloth
- [ ] Ogre
- [ ] Ogre zombi
- [ ] Ombre
- [ ] Oni
- [ ] Orog
- [ ] Orque
- [ ] Orque, chef de guerre
- [ ] Orque, Oeil de Gruumsh
- [ ] Otyugh
- [ ] Ours brun
- [ ] Ours des cavernes
- [ ] Ours noir
- [ ] Ours polaire
- [ ] Ours-garou
- [ ] Oxydeur
- [ ] Panthère
- [ ] Pégase
- [ ] Pentadrone
- [ ] Perforateur
- [ ] Péryton
- [ ] Pieuvre
- [ ] Pieuvre géante
- [ ] Piranha
- [ ] Pixie
- [ ] Planétar
- [ ] Plésiosaure
- [ ] Poing de Baine
- [ ] Poney
- [ ] Pouding noir
- [ ] Pousse de myconide
- [ ] Pseudodragon
- [ ] Ptéranodon
- [ ] Punaise de feu géante
- [ ] Quadrone
- [ ] Quaggoth
- [ ] Quaggoth, serviteur des spores
- [ ] Quasit
- [ ] Rakshasa
- [ ] Rat
- [ ] Rat géant
- [ ] Rat Géant (malade)
- [ ] Rat-garou
- [ ] Rémorhaz
- [ ] Rémorhaz, jeune
- [ ] Requin de récif
- [ ] Requin géant
- [ ] Requin-chasseur
- [ ] Résineux infecté
- [ ] Revenant
- [ ] Rhinocéros
- [ ] Roi/reine lézard
- [ ] Roturier
- [ ] Ruhk
- [ ] Sahuagin
- [ ] Sahuagin, baron
- [ ] Sahuagin, prêtresse
- [ ] Salamandre
- [ ] Sanglier
- [ ] Sanglier géant
- [ ] Sanglier-garou
- [ ] Satyre
- [ ] Saurial
- [ ] Scorpion
- [ ] Scorpion géant
- [ ] Serpent constricteur
- [ ] Serpent constricteur géant
- [ ] Serpent de feu
- [ ] Serpent venimeux
- [ ] Serpent venimeux géant
- [ ] Serpent volant
- [ ] Sibylle de l'eau
- [ ] Singe géant
- [ ] Slaad bleu
- [ ] Slaad funeste
- [ ] Slaad gris
- [ ] Slaad rouge
- [ ] Slaad vert
- [ ] Slaad, têtard
- [ ] Solar
- [ ] Spectateur
- [ ] Spectre
- [ ] Spore gazeuse
- [ ] Squelette
- [ ] Squelette de destrier
- [ ] Stirge
- [ ] Strahd von Zarovich
- [ ] Succube
- [ ] Succube/Incube
- [ ] Sylvanien
- [ ] Tabaxi, chasseur
- [ ] Tabaxi, ménestrel
- [ ] Tapis étrangleur
- [ ] Tarasque
- [ ] Tertre errant
- [ ] Tête de mort de Bhaal
- [ ] Thalasséen
- [ ] Thri-kreen
- [ ] Tiamat
- [ ] Tigre
- [ ] Tigre à dents de sabre
- [ ] Tigre-garou
- [ ] Torve
- [ ] Traqueur invisible
- [ ] Tricératops
- [ ] Tridrone
- [ ] Troglodyte
- [ ] Troll
- [ ] Tyramort
- [ ] Tyrannoeil
- [ ] Tyrannoeil zombi
- [ ] Tyrannosaure
- [ ] Ultroloth
- [ ] Vajra Safahr
- [ ] Vampire
- [ ] Vampirien
- [ ] Vase grise
- [ ] Vautour
- [ ] Vautour géant
- [ ] Ver pourpre
- [ ] Vétéran
- [ ] Vouivre
- [ ] Vrock
- [ ] Worg
- [ ] Xorn
- [ ] Yéti
- [ ] Yéti abominable
- [ ] Yochlol
- [ ] Yuan-ti, malison
- [ ] Yuan-ti, sang-pur
- [ ] Zombi

**Comment by davidR1974** [comment]
Ajouté :

Destrier
Belette
Ours-garou
Sanglier-garou
Rat-garou
Tigre-garou
Loup-garou
Nécrophage
Loup
Worg
Vouivre
Xorn
Zombi

Je fais dans l'ordre inverse des clés donc du nom du monstre mais en anglais :)

**Comment by adgranger** [comment]
Liste mise à jour au dessus, merci :)
